import type { Locale } from "@/lib/i18n";

const ru = {
  meta: {
    title: "Mehr Medical — многопрофильная клиника в Ташкенте (демо)",
    description:
      "Демо-сайт клиники от CaravanHouse: структура отделений, врачи с фильтрами, онлайн-запись по шагам, прайс с поиском и чек-апы.",
  },
  demo: {
    text: "Демо-сайт от CaravanHouse — клиника вымышленная, запись никуда не отправляется.",
    cta: "Заказать такой сайт",
  },
  nav: { structure: "Структура", doctors: "Врачи", prices: "Цены", checkups: "Чек-апы", branches: "Филиалы" },
  phone: "+998 71 000-00-00",
  book: "Записаться",
  bookShort: "Запись",
  langLabel: "Язык",
  menu: "Меню",
  close: "Закрыть",
  hero: {
    badgeToday: "Сегодня свободно {n} окон для записи",
    badgeTomorrow: "На завтра свободно {n} окон для записи",
    title: "Вся семья под присмотром",
    titleAccent: "одной клиники",
    subtitle: "12 отделений, 3 филиала и лаборатория с результатами онлайн. Запишитесь к врачу за минуту — без звонков и очередей.",
    searchPlaceholder: "Врач, услуга или анализ…",
    searchEmpty: "Ничего не нашли — попробуйте другое слово",
    searchDoctors: "Врачи",
    searchServices: "Услуги",
    quick: [
      { id: "book", label: "Запись к врачу" },
      { id: "lab", label: "Сдать анализы" },
      { id: "checkup", label: "Пройти чек-ап" },
      { id: "home", label: "Врач на дом" },
    ],
    stats: [
      { value: "12", label: "отделений" },
      { value: "16", label: "врачей" },
      { value: "3", label: "филиала" },
      { value: "07–22", label: "без выходных" },
    ],
    nextSlots: "Ближайшие окна",
    today: "Сегодня",
  },
  structure: {
    eyebrow: "Структура клиники",
    title: "Где какое отделение",
    subtitle: "Выберите филиал — и увидите, что на каком этаже. Нажмите на отделение, чтобы узнать подробности и записаться.",
    floor: "этаж",
    doctors: "врачей",
    services: "Основные услуги",
    centers: "Центры клиники",
    showDoctors: "Врачи отделения",
    admin: "Администрация и ресепшен",
    reception: "Ресепшен",
  },
  doctors: {
    eyebrow: "Врачи",
    title: "Найдите своего врача",
    subtitle: "Фильтр по отделению и языку приёма. У каждого врача видно ближайшее свободное время.",
    all: "Все",
    search: "Имя врача…",
    language: "Язык приёма",
    years: "лет опыта",
    from: "от",
    nextSlot: "Ближайшее окно",
    empty: "Нет врачей по этим фильтрам",
    showAll: "Показать всех врачей",
    langs: { ru: "RU", uz: "UZ", en: "EN" },
  },
  prices: {
    eyebrow: "Цены",
    title: "Прайс без звёздочек",
    subtitle: "Цены в сумах. Итоговая стоимость не меняется после приёма — всё согласуем заранее.",
    search: "Найти услугу…",
    all: "Все отделения",
    service: "Услуга",
    price: "Цена",
    empty: "Услуга не найдена",
    showAll: "Показать весь прайс",
    currency: "сум",
  },
  checkups: {
    eyebrow: "Чек-апы",
    title: "Обследование за один визит",
    subtitle: "Готовые программы со скидкой: все врачи и анализы в один день, итоговое заключение — в личном кабинете.",
    popular: "Популярный",
    choose: "Записаться на чек-ап",
    currency: "сум",
  },
  branches: {
    eyebrow: "Филиалы",
    title: "Три филиала в Ташкенте",
    route: "Как добраться",
  },
  faq: { eyebrow: "Пациентам", title: "Частые вопросы" },
  footer: {
    about: "Многопрофильная клиника для всей семьи. Демо-проект: все данные вымышленные.",
    made: "Сайт сделан командой CaravanHouse",
    rights: "Демо-проект",
  },
  booking: {
    title: "Запись на приём",
    steps: ["Отделение", "Врач", "Дата и время", "Контакты"],
    chooseDepartment: "Какое направление нужно?",
    chooseDoctor: "Выберите врача",
    anyDoctor: "Любой свободный врач",
    chooseDate: "Выберите день",
    chooseTime: "Свободное время",
    noSlots: "В этот день нет свободного времени",
    dayOff: "Выходной",
    name: "Имя и фамилия",
    phone: "Телефон",
    comment: "Комментарий для врача (необязательно)",
    back: "Назад",
    next: "Далее",
    confirm: "Подтвердить запись",
    errorName: "Укажите имя",
    errorPhone: "Укажите телефон",
    successTitle: "Вы записаны!",
    successText: "Это демо — на самом деле запись никуда не отправлена. В настоящем сайте пациент получил бы SMS и напоминание в Telegram.",
    addToCalendar: "Добавить в календарь",
    done: "Готово",
    summary: { doctor: "Врач", when: "Когда", where: "Где", price: "Стоимость" },
    currency: "сум",
  },
  weekdays: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
  months: ["января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря"],
};

export type UI = typeof ru;

const uz: UI = {
  meta: {
    title: "Mehr Medical — Toshkentdagi koʻp tarmoqli klinika (demo)",
    description:
      "CaravanHouse tayyorlagan klinika demo-sayti: boʻlimlar tuzilmasi, filtrli shifokorlar roʻyxati, bosqichma-bosqich onlayn yozilish, qidiruvli narxlar va chek-aplar.",
  },
  demo: {
    text: "CaravanHouse demo-sayti — klinika oʻylab topilgan, yozilish hech qayerga yuborilmaydi.",
    cta: "Shunday sayt buyurtma qilish",
  },
  nav: { structure: "Tuzilma", doctors: "Shifokorlar", prices: "Narxlar", checkups: "Chek-aplar", branches: "Filiallar" },
  phone: "+998 71 000-00-00",
  book: "Yozilish",
  bookShort: "Yozilish",
  langLabel: "Til",
  menu: "Menyu",
  close: "Yopish",
  hero: {
    badgeToday: "Bugun yozilish uchun {n} ta boʻsh vaqt bor",
    badgeTomorrow: "Ertaga yozilish uchun {n} ta boʻsh vaqt bor",
    title: "Butun oila",
    titleAccent: "bitta klinika nazoratida",
    subtitle: "12 ta boʻlim, 3 ta filial va natijalari onlayn keladigan laboratoriya. Shifokorga bir daqiqada yoziling — qoʻngʻiroq va navbatlarsiz.",
    searchPlaceholder: "Shifokor, xizmat yoki tahlil…",
    searchEmpty: "Hech narsa topilmadi — boshqa soʻz bilan urinib koʻring",
    searchDoctors: "Shifokorlar",
    searchServices: "Xizmatlar",
    quick: [
      { id: "book", label: "Shifokorga yozilish" },
      { id: "lab", label: "Tahlil topshirish" },
      { id: "checkup", label: "Chek-apdan oʻtish" },
      { id: "home", label: "Shifokorni uyga chaqirish" },
    ],
    stats: [
      { value: "12", label: "boʻlim" },
      { value: "16", label: "shifokor" },
      { value: "3", label: "filial" },
      { value: "07–22", label: "dam olishsiz" },
    ],
    nextSlots: "Eng yaqin boʻsh vaqtlar",
    today: "Bugun",
  },
  structure: {
    eyebrow: "Klinika tuzilmasi",
    title: "Qaysi boʻlim qayerda",
    subtitle: "Filialni tanlang — qaysi qavatda nima borligini koʻrasiz. Batafsil maʼlumot va yozilish uchun boʻlimni bosing.",
    floor: "qavat",
    doctors: "shifokor",
    services: "Asosiy xizmatlar",
    centers: "Klinika markazlari",
    showDoctors: "Boʻlim shifokorlari",
    admin: "Maʼmuriyat va qabulxona",
    reception: "Qabulxona",
  },
  doctors: {
    eyebrow: "Shifokorlar",
    title: "Oʻz shifokoringizni toping",
    subtitle: "Boʻlim va qabul tili boʻyicha filtr. Har bir shifokorning eng yaqin boʻsh vaqti koʻrinadi.",
    all: "Hammasi",
    search: "Shifokor ismi…",
    language: "Qabul tili",
    years: "yillik tajriba",
    from: "",
    nextSlot: "Eng yaqin vaqt",
    empty: "Bu filtrlar boʻyicha shifokor yoʻq",
    showAll: "Barcha shifokorlarni koʻrsatish",
    langs: { ru: "RU", uz: "UZ", en: "EN" },
  },
  prices: {
    eyebrow: "Narxlar",
    title: "Yashirin toʻlovlarsiz narxlar",
    subtitle: "Narxlar soʻmda. Yakuniy narx qabuldan keyin oʻzgarmaydi — hammasi oldindan kelishiladi.",
    search: "Xizmatni topish…",
    all: "Barcha boʻlimlar",
    service: "Xizmat",
    price: "Narx",
    empty: "Xizmat topilmadi",
    showAll: "Toʻliq narxlar roʻyxati",
    currency: "soʻm",
  },
  checkups: {
    eyebrow: "Chek-aplar",
    title: "Bir tashrifda toʻliq tekshiruv",
    subtitle: "Chegirmali tayyor dasturlar: barcha shifokorlar va tahlillar bir kunda, yakuniy xulosa — shaxsiy kabinetda.",
    popular: "Ommabop",
    choose: "Chek-apga yozilish",
    currency: "soʻm",
  },
  branches: {
    eyebrow: "Filiallar",
    title: "Toshkentda uchta filial",
    route: "Qanday borish mumkin",
  },
  faq: { eyebrow: "Bemorlarga", title: "Koʻp beriladigan savollar" },
  footer: {
    about: "Butun oila uchun koʻp tarmoqli klinika. Demo-loyiha: barcha maʼlumotlar oʻylab topilgan.",
    made: "Sayt CaravanHouse jamoasi tomonidan yaratilgan",
    rights: "Demo-loyiha",
  },
  booking: {
    title: "Qabulga yozilish",
    steps: ["Boʻlim", "Shifokor", "Sana va vaqt", "Aloqa"],
    chooseDepartment: "Qaysi yoʻnalish kerak?",
    chooseDoctor: "Shifokorni tanlang",
    anyDoctor: "Istalgan boʻsh shifokor",
    chooseDate: "Kunni tanlang",
    chooseTime: "Boʻsh vaqt",
    noSlots: "Bu kunda boʻsh vaqt yoʻq",
    dayOff: "Dam olish",
    name: "Ism va familiya",
    phone: "Telefon",
    comment: "Shifokor uchun izoh (ixtiyoriy)",
    back: "Orqaga",
    next: "Keyingi",
    confirm: "Yozilishni tasdiqlash",
    errorName: "Ismingizni kiriting",
    errorPhone: "Telefon raqamini kiriting",
    successTitle: "Siz yozildingiz!",
    successText: "Bu demo — aslida yozilish hech qayerga yuborilmadi. Haqiqiy saytda bemor SMS va Telegramda eslatma olardi.",
    addToCalendar: "Taqvimga qoʻshish",
    done: "Tayyor",
    summary: { doctor: "Shifokor", when: "Qachon", where: "Qayerda", price: "Narx" },
    currency: "soʻm",
  },
  weekdays: ["Ya", "Du", "Se", "Ch", "Pa", "Ju", "Sh"],
  months: ["yanvar", "fevral", "mart", "aprel", "may", "iyun", "iyul", "avgust", "sentabr", "oktabr", "noyabr", "dekabr"],
};

const dictionaries: Record<Locale, UI> = { ru, uz };
export const getUI = (lang: Locale) => dictionaries[lang];
